import { Lexend } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Procar.az - Sizin Elektromobil Platformanız",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="tb8nMv-7jPlzcRs5SlVoiQOZbrCJMPqnQ5rvxkm7Jxg"
      />
      <body className={`${lexend.className} antialiased`}>{children}</body>
    </html>
  );
}
